In [ ]:
import pandas as pd

df = pd.read_csv("../DATA/raw/loans_raw.csv")
df.head()

In [5]:
df = pd.read_csv("../DATA/raw/loans_raw.csv")

In [6]:
df.head()

,loan_id,applicant_id,customer_name,gender,date_of_birth,age,marital_status,education,occupation,employment_type,...,recovery_amount,loan_officer_id,loan_officer_name,payment_history_score,bounce_count,risk_category,customer_segment,is_fraud_suspected,kyc_verified,channel
0,LN157322,AP257322,Sunil Mukherjee,Male,1998-10-02,28,Married,Post Graduate,Retail Business Owner,Business Owner,...,95223.0,OFF0073,Vivaan Kulkarni,446.0,5,Low,Mass Market,No,Yes,Digital App
1,LN200595,AP300595,Dinesh Naidu,Male,2003-04-13,23,Married,Post Graduate,Trading Company Owner,Business Owner,...,0.0,OFF0080,Aarav Patil,900.0,1,Low,Mass Market,No,Yes,Digital App
2,LN152399,AP252399,Karan Naidu,Male,1990-02-11,36,Divorced,Professional Degree,Manager,Salaried,...,0.0,OFF0112,Usha Sinha,836.0,1,Low,Mass Affluent,No,Yes,Branch Walk-in
3,LN192773,AP292773,Vihaan Rathore,Male,1979-11-04,47,Married,Professional Degree,Bank Employee,Salaried,...,0.0,OFF0015,Aarav More,868.0,0,Low,Premium,No,Yes,Corporate Tie-up
4,LN133442,AP233442,Komal Pillai,Female,1974-11-06,52,Married,Post Graduate,Freelancer,Self-Employed Business,...,0.0,OFF0146,Sneha Bhatt,882.0,0,Low,Mass Market,No,Yes,Tele-calling

In [7]:
df.head()

,loan_id,applicant_id,customer_name,gender,date_of_birth,age,marital_status,education,occupation,employment_type,...,recovery_amount,loan_officer_id,loan_officer_name,payment_history_score,bounce_count,risk_category,customer_segment,is_fraud_suspected,kyc_verified,channel
0,LN157322,AP257322,Sunil Mukherjee,Male,1998-10-02,28,Married,Post Graduate,Retail Business Owner,Business Owner,...,95223.0,OFF0073,Vivaan Kulkarni,446.0,5,Low,Mass Market,No,Yes,Digital App
1,LN200595,AP300595,Dinesh Naidu,Male,2003-04-13,23,Married,Post Graduate,Trading Company Owner,Business Owner,...,0.0,OFF0080,Aarav Patil,900.0,1,Low,Mass Market,No,Yes,Digital App
2,LN152399,AP252399,Karan Naidu,Male,1990-02-11,36,Divorced,Professional Degree,Manager,Salaried,...,0.0,OFF0112,Usha Sinha,836.0,1,Low,Mass Affluent,No,Yes,Branch Walk-in
3,LN192773,AP292773,Vihaan Rathore,Male,1979-11-04,47,Married,Professional Degree,Bank Employee,Salaried,...,0.0,OFF0015,Aarav More,868.0,0,Low,Premium,No,Yes,Corporate Tie-up
4,LN133442,AP233442,Komal Pillai,Female,1974-11-06,52,Married,Post Graduate,Freelancer,Self-Employed Business,...,0.0,OFF0146,Sneha Bhatt,882.0,0,Low,Mass Market,No,Yes,Tele-calling

In [8]:
df.shape

(120720, 53)

In [9]:
df.columns.tolist()

['loan_id',
 'applicant_id',
 'customer_name',
 'gender',
 'date_of_birth',
 'age',
 'marital_status',
 'education',
 'occupation',
 'employment_type',
 'employer_name',
 'years_with_employer',
 'annual_income',
 'monthly_income',
 'city',
 'state',
 'pincode',
 'branch_id',
 'branch_name',
 'region',
 'loan_product',
 'loan_purpose',
 'loan_amount',
 'sanctioned_amount',
 'disbursed_amount',
 'interest_rate',
 'tenure_months',
 'emi_amount',
 'processing_fee',
 'credit_score',
 'debt_to_income_ratio',
 'existing_loans_count',
 'existing_emi_obligations',
 'collateral_type',
 'collateral_value',
 'co_applicant_flag',
 'application_date',
 'approval_date',
 'disbursal_date',
 'loan_status',
 'default_flag',
 'days_past_due',
 'npa_flag',
 'recovery_amount',
 'loan_officer_id',
 'loan_officer_name',
 'payment_history_score',
 'bounce_count',
 'risk_category',
 'customer_segment',
 'is_fraud_suspected',
 'kyc_verified',
 'channel']

In [ ]:
df.info()

In [ ]:
df[['date_of_birth',
    'application_date',
    'approval_date',
    'disbursal_date']].head()

In [ ]:
date_columns =[
    "date_of_birth",
    "application_date",
    "approval_date",
    "disbursal_date"]
for col in date_columns:
    df[col]=pd.to_datetime(df[col],format="mixed",dayfirst=True)

In [ ]:
df.info()

In [ ]:
missing = df.isnull().sum()

missing = missing[missing > 0]

missing.sort_values(ascending=False)
print(missing)

In [ ]:
df.groupby("loan_product")["collateral_type"].apply(lambda x: x.isnull().sum())

In [ ]:
df[['annual_income', 'monthly_income']].head(10)

In [ ]:
df[['annual_income', 'monthly_income']].isnull().sum()

In [ ]:
(df["annual_income"]/12).round(0).head(10)

In [ ]:
df[['annual_income', 'monthly_income']].head(10)

In [ ]:
df["monthly_income"].head(10)

In [ ]:
df[["annual_income", "monthly_income"]].isnull().sum()

In [ ]:
df[df["annual_income"].isnull() & df["monthly_income"].isnull()][["annual_income","monthly_income"]].head(10)

In [ ]:
# Fill Annual Income
df["annual_income"] = df["annual_income"].fillna(df["monthly_income"] * 12)

# Fill Monthly Income
df["monthly_income"] = df["monthly_income"].fillna(df["annual_income"] / 12)

In [ ]:
df[df["annual_income"].isnull()].groupby("loan_product").size()

In [ ]:
df[df["annual_income"].isnull()].isnull().sum()

In [ ]:
df["annual_income"] = df["annual_income"].fillna(
    df.groupby("loan_product")["annual_income"].transform("median")
)

df["monthly_income"] = df["monthly_income"].fillna(
    df.groupby("loan_product")["monthly_income"].transform("median")
)

In [ ]:
# ================================
# Credit Score Validation & Cleaning
# ================================

In [ ]:
# Step 2: Credit Score Validation & Cleaning

#Objective:Validate the credit score column, identify missing values, check the valid range, and decide the best cleaning strategy based on business logic.

In [ ]:
#Missing Values
print("Missing Values:", df["credit_score"].isnull().sum())

In [ ]:
# Minimum and Maximum Credit Score
print("Minimum Credit Score:", df["credit_score"].min())
print("Maximum Credit Score:", df["credit_score"].max())

In [ ]:
df["credit_score"].describe()

In [ ]:
# median are less effect by outliers
df["credit_score"].fillna(
    df["credit_score"].median()
)

In [ ]:
df["credit_score"] = df["credit_score"].fillna(
    df["credit_score"].median()
)

In [ ]:
df["credit_score"].isnull().sum()

In [ ]:
df["credit_score"] = df["credit_score"].fillna(
    df["credit_score"].median()
)

df["credit_score"].isnull().sum()

In [ ]:
### Credit Score Cleaning

#**Observation:**
#- Missing Values: 5074
#- Valid Range: 300 900
#- Median Credit Score: 680

#**Cleaning Strategy:**
#Filled missing values using the median because the median is less affected by outliers than the mean.

#**Result:**
#Missing values reduced from 5074 to 0.

In [ ]:
df[df["employer_name"].isnull()][
    ["employment_type", "employer_name", "years_with_employer"]
].head(20)

In [ ]:
df["employer_name"] = df["employer_name"].fillna("Unknown")

In [ ]:
df["years_with_employer"].isnull().sum()

In [ ]:
df[df["years_with_employer"].isnull()].groupby("employment_type").size()

In [ ]:
df["years_with_employer"] = df["years_with_employer"].fillna(
    df.groupby("employment_type")["years_with_employer"].transform("median")
)

In [ ]:
df["years_with_employer"] = df["years_with_employer"].fillna(
    df.groupby("employment_type")["years_with_employer"].transform("median")
)

df["years_with_employer"].isnull().sum()

In [ ]:
df[df["employer_name"].isnull()].groupby("employment_type").size()

In [ ]:
df["co_applicant_flag"].value_counts(dropna=False)

In [ ]:
#Check Missing Values by Loan Status
df[df["co_applicant_flag"].isnull()]["loan_status"].value_counts()

In [ ]:
#Check Missing Values by Employment Type
df[df["co_applicant_flag"].isnull()]["employment_type"].value_counts()

In [ ]:
df[df["co_applicant_flag"].isnull()]["loan_product"].value_counts()

In [ ]:
# Overall distribution
df["co_applicant_flag"].value_counts(normalize=True, dropna=False) * 100

In [ ]:
# Loan status vs Co-applicant
pd.crosstab(
    df["loan_status"],
    df["co_applicant_flag"],
    normalize="index"
) * 100

In [ ]:
df["co_applicant_flag"] = df["co_applicant_flag"].fillna("No")

In [ ]:
df["co_applicant_flag"].isnull().sum()

In [ ]:
#Collateral Type
df["collateral_type"].isnull().sum()

In [ ]:
df["collateral_type"].value_counts(dropna=False)

In [ ]:
df[df["collateral_type"].isnull()]["loan_product"].value_counts()

In [ ]:
df[df["collateral_type"].isnull()]["loan_status"].value_counts()

In [ ]:
df["collateral_type"] = df["collateral_type"].fillna("No Collateral")

In [ ]:
df["collateral_type"] = df["collateral_type"].fillna("No Collateral")

In [ ]:
df["collateral_type"].isnull().sum()

In [ ]:
df["collateral_type"].value_counts()

In [ ]:
df.to_csv("../DATA/cleaned_loan_data.csv", index=False)
print("Cleaned dataset saved successfully!")

In [3]:
df.isnull().sum()

NameError: name 'df' is not defined

In [ ]:
df.isnull().sum()

In [ ]:
df.duplicated().sum()

In [ ]:
df.info()

In [ ]:
print(df.shape)

In [1]:
print("Hello")

Hello

In [2]:
import pandas as pd
print("Pandas Loaded")

Pandas Loaded

In [7]:
df.isnull().sum()

loan_id                         0
applicant_id                    0
customer_name                   0
gender                          0
date_of_birth                   0
age                             0
marital_status                  0
education                       0
occupation                      0
employment_type                 0
employer_name                3852
years_with_employer          4720
annual_income                5911
monthly_income               5366
city                            0
state                           0
pincode                         0
branch_id                       0
branch_name                     0
region                          0
loan_product                    0
loan_purpose                    0
loan_amount                     0
sanctioned_amount               0
disbursed_amount                0
interest_rate                   0
tenure_months                   0
emi_amount                      0
processing_fee                  0
credit_score                 5074
debt_to_income_ratio            0
existing_loans_count            0
existing_emi_obligations        0
collateral_type             72313
collateral_value             4096
co_applicant_flag            5067
application_date                0
approval_date                   0
disbursal_date                  0
loan_status                     0
default_flag                    0
days_past_due                5220
npa_flag                        0
recovery_amount              4809
loan_officer_id                 0
loan_officer_name               0
payment_history_score        4598
bounce_count                    0
risk_category                   0
customer_segment                0
is_fraud_suspected              0
kyc_verified                    0
channel                         0
dtype: int64

In [8]:
df["employer_name"] = df["employer_name"].fillna("Unknown")

In [9]:
df["years_with_employer"] = (
    df.groupby("employment_type")["years_with_employer"]
      .transform(lambda x: x.fillna(x.median()))
)

In [10]:
df["annual_income"] = df["annual_income"].fillna(df["annual_income"].median())

In [11]:
df["credit_score"] = df["credit_score"].fillna(df["credit_score"].median())

In [12]:
df["co_applicant_flag"] = df["co_applicant_flag"].fillna("No")

In [13]:
df["recovery_amount"] = df["recovery_amount"].fillna(0)

In [14]:
df["days_past_due"] = df["days_past_due"].fillna(0)

In [15]:
df["payment_history_score"] = df["payment_history_score"].fillna(
    df["payment_history_score"].median()
)

In [16]:
df["collateral_type"] = df["collateral_type"].fillna("None")
df["collateral_value"] = df["collateral_value"].fillna(0)

In [19]:
df.isnull().sum()

loan_id                     0
applicant_id                0
customer_name               0
gender                      0
date_of_birth               0
age                         0
marital_status              0
education                   0
occupation                  0
employment_type             0
employer_name               0
years_with_employer         0
annual_income               0
monthly_income              0
city                        0
state                       0
pincode                     0
branch_id                   0
branch_name                 0
region                      0
loan_product                0
loan_purpose                0
loan_amount                 0
sanctioned_amount           0
disbursed_amount            0
interest_rate               0
tenure_months               0
emi_amount                  0
processing_fee              0
credit_score                0
debt_to_income_ratio        0
existing_loans_count        0
existing_emi_obligations    0
collateral_type             0
collateral_value            0
co_applicant_flag           0
application_date            0
approval_date               0
disbursal_date              0
loan_status                 0
default_flag                0
days_past_due               0
npa_flag                    0
recovery_amount             0
loan_officer_id             0
loan_officer_name           0
payment_history_score       0
bounce_count                0
risk_category               0
customer_segment            0
is_fraud_suspected          0
kyc_verified                0
channel                     0
dtype: int64

In [17]:
df.isnull().sum()

loan_id                        0
applicant_id                   0
customer_name                  0
gender                         0
date_of_birth                  0
age                            0
marital_status                 0
education                      0
occupation                     0
employment_type                0
employer_name                  0
years_with_employer            0
annual_income                  0
monthly_income              5366
city                           0
state                          0
pincode                        0
branch_id                      0
branch_name                    0
region                         0
loan_product                   0
loan_purpose                   0
loan_amount                    0
sanctioned_amount              0
disbursed_amount               0
interest_rate                  0
tenure_months                  0
emi_amount                     0
processing_fee                 0
credit_score                   0
debt_to_income_ratio           0
existing_loans_count           0
existing_emi_obligations       0
collateral_type                0
collateral_value               0
co_applicant_flag              0
application_date               0
approval_date                  0
disbursal_date                 0
loan_status                    0
default_flag                   0
days_past_due                  0
npa_flag                       0
recovery_amount                0
loan_officer_id                0
loan_officer_name              0
payment_history_score          0
bounce_count                   0
risk_category                  0
customer_segment               0
is_fraud_suspected             0
kyc_verified                   0
channel                        0
dtype: int64

In [18]:
df["monthly_income"] = df["monthly_income"].fillna(df["annual_income"] / 12)

In [20]:
df.isnull().sum()

loan_id                     0
applicant_id                0
customer_name               0
gender                      0
date_of_birth               0
age                         0
marital_status              0
education                   0
occupation                  0
employment_type             0
employer_name               0
years_with_employer         0
annual_income               0
monthly_income              0
city                        0
state                       0
pincode                     0
branch_id                   0
branch_name                 0
region                      0
loan_product                0
loan_purpose                0
loan_amount                 0
sanctioned_amount           0
disbursed_amount            0
interest_rate               0
tenure_months               0
emi_amount                  0
processing_fee              0
credit_score                0
debt_to_income_ratio        0
existing_loans_count        0
existing_emi_obligations    0
collateral_type             0
collateral_value            0
co_applicant_flag           0
application_date            0
approval_date               0
disbursal_date              0
loan_status                 0
default_flag                0
days_past_due               0
npa_flag                    0
recovery_amount             0
loan_officer_id             0
loan_officer_name           0
payment_history_score       0
bounce_count                0
risk_category               0
customer_segment            0
is_fraud_suspected          0
kyc_verified                0
channel                     0
dtype: int64

In [21]:
df.to_csv("../DATA/cleaned_loan_data.csv", index=False)
print("✅ Cleaned dataset saved successfully!")

✅ Cleaned dataset saved successfully!

In [22]:
import os
print(os.listdir("../DATA"))

['cleaned_loan_data.csv', 'raw']